title: Website Title
description: >
  Website Description
author:
  name: GitHub User
  email: your-email@domain.com

nav_pages:
  - about.md

show_excerpts: true
show_rss_feed: true

plugins:
  - jekyll-feed
  - jekyll-seo-tag

content_selector: div.post-content,div.home
ghbase: schh-commons/website-template/main
url: /website-template