title: Website Title
description: >
  Website Description
author:
  name: Name
  email: your-email@domain.com

nav_pages:
  - about.md
  - contact.md

show_excerpts: true
show_rss_feed: true

plugins:
  - jekyll-feed
  - jekyll-seo-tag

content_selector: div.post-content,div.home
